#!/bin/bash

CPATH=.
CPATH=$CPATH:lib/log4j-1.2.13.jar
CPATH=$CPATH:lib/antlr-3.2.jar
CPATH=$CPATH:lib/commons-io-2.1.jar
CPATH=$CPATH:lib/commons-lang-2.4.jar
CPATH=$CPATH:build/classes
CPATH=$CPATH:target
CPATH=$CPATH:target/classes

# To set the page-size to use, add "-Dnanodb.pagesize=2048" to JAVA_OPTS.
# To enable transaction processing, add "-Dnanodb.txns=on" to JAVA_OPTS.
#JAVA_OPTS="-Dlog4j.configuration=logging.conf"

java $JAVA_OPTS -cp $CPATH com.wind.nanodb.client.ExclusiveClient
